name: cpv
channels:
  - conda-forge
dependencies:
  - python=3.7.3
  - pip
  - pip:
    - gym
    - gym-craftingworld
    - six
    - torch
    - torchvision
    - tensorboardX
    - black
    - natsort
    - opencv-python
    - pillow
